<?xml version="1.0"?>
<robot name="ciiivtol" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Import RViz colors -->
    <xacro:include filename="$(find vtol_description)/urdf/material.xacro" />

    <!-- Robot parameters file -->
    <xacro:include filename="$(find vtol_description)/urdf/params.xacro" />

    <!-- Macro for VTOL parts (lateral, motor and propeller -->
    <xacro:include filename="$(find vtol_description)/urdf/lateral.xacro" />
    <xacro:include filename="$(find vtol_description)/urdf/motor.xacro" />
    <xacro:include filename="$(find vtol_description)/urdf/propeller.xacro" />

    <!-- Gazebo elements materials and plugins -->
    <xacro:include filename="$(find vtol_description)/urdf/ciii_vtol.gazebo" />

    <!-- Fixed world link -->
    <link name="world_link" />

    <!-- Base -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://vtol_description/meshes/base.stl" />
            </geometry>
            <material name="brown" />
        </visual>
        <collision>
            <origin xyz="0 0 ${B_z / 2}" rpy="0 0 0" />
            <geometry>
                <box size="${B_x} ${B_y} ${B_z}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${B_mass}" />
            <inertia ixx="${B_Ixx}" ixy="0" ixz="0" 
                iyy="${B_Iyy}" iyz="0" izz="${B_Izz}" />
        </inertial>
    </link>
    <joint name="world_link" type="fixed">
        <parent link="world_link" />
        <child link="base_link" />
    </joint>

    <!-- Laterals -->
    <xacro:vtol_lateral name="front" origin_xyz="0 -0.019 0.150" />
    <xacro:vtol_lateral name="rear" origin_xyz="0  0.019 0.150" />

    <!-- Crossbar -->
    <link name="crossbar_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://vtol_description/meshes/crossbar.stl" />
            </geometry>
            <material name="brown" />
        </visual>
        <collision>
            <origin xyz="0 0 ${C_z / 2}" rpy="0 0 0" />
            <geometry>
                <box size="${C_x} ${C_y} ${C_z}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${C_mass}" />
            <inertia ixx="${C_Ixx}" ixy="0" ixz="0" 
                iyy="${C_Iyy}" iyz="0" izz="${C_Izz}" />
        </inertial>
    </link>
    <joint name="crossbar_joint" type="fixed">
        <origin xyz="0 0 0.111" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="crossbar_link" />
    </joint>

    <!-- Axis suppport (front & rear) -->
    <link name="support_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://vtol_description/meshes/axis_support.stl" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="0 0 0.013" rpy="0 0 0" />
            <geometry>
                <box size="0.050 0.026 0.042" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0.016" rpy="0 0 0" />
            <mass value="0.068250" />
            <inertia ixx="0.000013878" ixy="0" ixz="0" 
                iyy="0.000024252" iyz="0" izz="0.000018064" />
        </inertial>
        -->
    </link>
    <joint name="support_joint" type="continuous">
        <!--
        <dynamics damping="0.001" friction="0.001" />
        <limit effort="30.0" velocity="10.0" lower="${-20.0 * pi / 180.0}" upper="${20.0 * pi / 180.0}" />
        -->
        <origin xyz="0 0 0.150" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="support_link" />
        <axis xyz="0 1 0" />
    </joint>

    <!-- Main bar -->
    <link name="bar_link">
        <visual xyz="0 0 0" rpy="0 0 0">
            <origin xyz="0 0 0.016" rpy="0 0 0" />
            <geometry>
                <box size="${MB_L} ${MB_w_out} ${MB_w_out}" rpy="0 0 0"/>
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0 0 0.016" rpy="0 0 0" />
            <geometry>
                <box size="${MB_L} ${MB_w_out} ${MB_w_out}" rpy="0 0 0"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${MB_mass}" />
            <inertia ixx="${MB_Ixx}" ixy="0" ixz="0" iyy="${MB_Iyy}" iyz="0" izz="${MB_Iyy}" />
        </inertial>
    </link>
    <joint name="bar_joint" type="fixed">
        <parent link="support_link" />
        <child link="bar_link" />
    </joint>

    <!-- Left & Right motors -->
    <xacro:motor name="lmotor" origin_xyz="-0.225 0 0.0435" />
    <xacro:motor name="rmotor" origin_xyz="0.225 0 0.0435" />

    <!-- Left & Right propellers -->
    <xacro:propeller name="lprop" parent="lmotor" />
    <xacro:propeller name="rprop" parent="rmotor" />

    <!-- IMU sensor -->
    <link name="imu_link">
        <visual xyz="0 0 0" rpy="0 0 0">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.02 0.02 0.01" />
            </geometry>
            <material name="gray" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.02 0.02 0.01" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.001" />
            <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001"/>
        </inertial>
    </link>
    <joint name="imu_joint" type="fixed">
        <origin xyz="0 0 0.05" />
        <parent link="bar_link" />
        <child link="imu_link" />
    </joint>

</robot>
