<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Density so that the base weights more that 10 Kg -->
    <xacro:property name="rho_B" value="100.0" />

    <!-- Density of MDF: 600-800 Kg/m^3 -->
    <xacro:property name="rho_mdf" value="0.7" />

    <!-- Base -->
    <xacro:property name="B_x" value="0.200" />
    <xacro:property name="B_y" value="0.060" />
    <xacro:property name="B_z" value="0.009" />
    <xacro:property name="B_vol" value="${B_x * B_y * B_z}" />
    <xacro:property name="B_mass" value="${1000.0 * B_vol * rho_B}" />
    <xacro:property name="B_Ixx" value="${(1/12) * B_mass * (B_y**2 + B_z**2)}" />
    <xacro:property name="B_Iyy" value="${(1/12) * B_mass * (B_x**2 + B_z**2)}" />
    <xacro:property name="B_Izz" value="${(1/12) * B_mass * (B_x**2 + B_y**2)}" />

    <!-- Laterals -->
    <xacro:property name="L_x" value="0.050" />
    <xacro:property name="L_y" value="0.009" />
    <xacro:property name="L_z" value="0.170" />
    <xacro:property name="L_vol" value="${L_x * L_y * L_z}" />
    <xacro:property name="L_mass" value="${1000.0 * L_vol * rho_mdf}" />
    <xacro:property name="L_Ixx" value="${(1/12) * L_mass * (L_y**2 + L_z**2)}" />
    <xacro:property name="L_Iyy" value="${(1/12) * L_mass * (L_x**2 + L_z**2)}" />
    <xacro:property name="L_Izz" value="${(1/12) * L_mass * (L_x**2 + L_y**2)}" />

    <!-- Crossbar -->
    <xacro:property name="C_x" value="0.050" />
    <xacro:property name="C_y" value="0.047" />
    <xacro:property name="C_z" value="0.009" />
    <xacro:property name="C_vol" value="${C_x * C_y * C_z}" />
    <xacro:property name="C_mass" value="${1000.0 * C_vol * rho_mdf}" />
    <xacro:property name="C_Ixx" value="${(1/12) * C_mass * (C_y**2 + C_z**2)}" />
    <xacro:property name="C_Iyy" value="${(1/12) * C_mass * (C_x**2 + C_z**2)}" />
    <xacro:property name="C_Izz" value="${(1/12) * C_mass * (C_x**2 + C_y**2)}" />

    <!-- Main bar -->
    <xacro:property name="MB_rho" value="2.7" />
    <xacro:property name="MB_w_out" value="0.020" />
    <xacro:property name="MB_thickness" value="0.0016" />
    <xacro:property name="MB_w_in" value="${MB_w_out - 2*MB_thickness}" />
    <xacro:property name="MB_L" value="0.500" />
    <xacro:property name="MB_vol" value="${(MB_w_out**2 - MB_w_in**2) * MB_L}" />
    <xacro:property name="MB_mass" value="${1000.0 * MB_vol * MB_rho}" />
    <xacro:property name="MB_Ixx" value="${(1/12) * MB_mass * 2 * MB_w_out**2}" />
    <xacro:property name="MB_Iyy" value="${(1/12) * MB_mass * (MB_w_out**2 + MB_L**2)}" />

</robot>
